### ISSUE TITLE
Version 2.0.2 on crates.io doesn't build

### ISSUE THREAD

**Issue by 1tgr** [jordanbray/chess#14]
It produces a lot of errors, starting with:

```rust
~/.cargo/bin/cargo check --color=always --all --all-targets
   Compiling chess v2.0.2
error[E0433]: failed to resolve: use of undeclared type or module `gen_tables`
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/chess-2.0.2/src/gen_tables/bmis.rs:6:5
  |
6 | use gen_tables::magic_helpers::{magic_mask, questions_and_answers, NUM_MOVES};
  |     ^^^^^^^^^^ use of undeclared type or module `gen_tables`
```

That code would build on Rust 2015, but version 2.0.2 is marked as Rust 2018.

Version 2.0.1 (the latest version committed to this repo) is still Rust 2015 and it works fine.

**Comment by jordanbray** [comment]
This is fixed in the next version, which I'm planning to push out today.

**Comment by jordanbray** [comment]
Fixed in 3.0.0.  Major version number bump due to minor API changes.
